### ISSUE TITLE
Reporte del Aportante

### ISSUE THREAD

**Issue by mayoricodevault** [rodrigopbel/ong#2]

**Comment by rodrigopbel** [comment]
Miguel olvide una cosa mas actualmente el beneficiario tiene un campo que
se puede cambiar de "Activo o inactivo " pero no esta funcionando es decir
no hace nada si se podría usar ese campo para q cuando lo pongas en
Inactivo quite a ese beneficiario de los combo box que jalan a ese
beneficiario es decir deshabilitarlo de donaciones y ayudas

2016-01-16 10:13 GMT-04:00 Mike Mayori notifications@github.com:
